---
run:
  timeout: 3m

linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocyclo:
    min-complexity: 16
  godot:
    check-all: true
  goimports:
    local-prefixes: github.com/go-crypt/crypt

linters:
  enable:
    - asciicheck
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - gosec
    - misspell
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - whitespace
    - wsl

issues:
  exclude:
    -  'SA4011: ineffective break statement. Did you mean to break out of the outer loop'
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
...
